
#ifndef __ovCoAdaptP300Visualiser__
#define __ovCoAdaptP300Visualiser__

#include <iostream>

#if defined TARGET_HAS_ThirdPartyModulesForCoAdaptStimulator

#include <openvibe/ov_all.h>
#include <toolkit/ovtk_all.h>

#include <queue>

#include <cstdio>
#include <cstdlib>

#include "src/stimulator/ovexP300CStimulator.h"
#include "src/stimulator/ovexP300CNULLStimulator.h"

#include "src/tagging/ovexCSoftTagger.h"
#if defined TARGET_OS_Linux || (defined TARGET_OS_Windows && defined TARGET_HAS_ThirdPartyInpout)
#include "src/tagging/ovexParallelPort.h"
#endif


#include "src/visualisation/glP300MainContainer.h"

#include "src/properties/ovexP300InterfacePropertyReader.h"
#include "src/properties/ovexP300StimulatorPropertyReader.h"
#include "src/properties/ovexP300ScreenLayoutReader.h"

#include "src/sequence/ovexP300RipRandSequenceGenerator.h"
#include "src/sequence/ovexP300RowColumnSequenceGenerator.h"
#include "src/sequence/ovexP300CSVReader.h"

#include "src/ovexP300SequenceFileWriter.h"

#include "src/evidence-accumulation/ovexP300CEvidenceAccumulator.h"

#include "src/ova_defines.h"

namespace OpenViBEApplications
{
		/**
		* The implementation file includes the main function (press 's' to start the stimulator). 
		* The class itself will receive events from the stimulator CoAdaptP300Stimulator through the processCallback function.
		* Based on those events/stimuli it will make the appropriate calls for displaying the flashes. 
		* To update the states of the keys from flash to non-flash state for example it notifies the P300KeyboardHandler
		* which will notify the keys that need to be changed. The keys are then replaced by other keys of the required state.
		* However this does not display anything on the screen yet. For this we have to call the drawAndSync method of 
		* the P300MainContainer class. This will call the draw function on all the tables/containers on the screen which in turn will
		* call the draw function of all the children in those containers/tables, eventually drawing the buttons/symbols.
		* Property files are read by the CoAdaptP300PropertyReader classes, stimuli generated by the P300SequenceGenerator
		* classes and communication with openvibe is done by the ISharedMemoryReader and CoAdaptP300SharedMemoryReader classes
		* Furthermore some keys have special actions associated with them which are handled by the handler classes.
		*/
		class CoAdaptP300Visualiser
		{

		public:

			/**
			 * Constructor initializes some private working variables
			 */
			CoAdaptP300Visualiser();
			
			/**
			 * Deconstructor deletes the stimulator object, the tagger object and all the property readers
			 */
			~CoAdaptP300Visualiser();

			/**
			 * This function is called by processCallback. Based on the event received by the stimulator it will call the necessary functions.
			 * @param event the stimulus or event number. For a list of the stimuli you can take a look in the ova_defines.h file.
			 */
			void process(OpenViBE::uint32 event);
			
			/**
			 * This is the callback function called by the stimulator CoAdaptP300Stimulator in case of an event. It calls the process function
			 * @param event the stimulus or event number. For a list of the stimuli you can take a look in the ova_defines.h file.
			 */
			static void processCallback(OpenViBE::uint32 event);

			/**
			 * This is the callback function called when we have to wait for events
			 * @param 0 if we immediately process all queued events, otherwise we wait for an event
			 */
			static void processWaitCallback(OpenViBE::uint32 waiting);


			/**
			 * This function checks for the order to quit the application (from the user or the stimulator)
			 * @return true if we quit, false otherwise
			 */
			static OpenViBE::boolean areWeQuitting(void);

			/**
			 * Initializes the OpenViBE kernel so that we can use some facilities such as the LogManager
			 */
			void initializeOpenViBEKernel();
			
			/**
			 * 
			 */
			void start();
			
			/**
			 * 
			 */
			OpenViBE::uint32 getNumberOfKeys() { return m_pScreenLayoutReader->getNumberOfKeys(); }

			const P300MainContainer* getMainContainer() { return m_pMainContainer;}

			const OpenViBE::boolean getReplayMode() {return m_bReplayMode;}

		private:
			
			/**
			 * Iterates over states and changes the value at each index either to ifState or elseState depending on the current value (either one or zero) 
			 * @param states contains either a zero or one for each symbol on the keyboard
			 * @param ifState in case states[i]==1 it will replace the state to ifState
			 * @param elseState in case states[i]==1 it will replace the state to elseState
			 */
			void changeStates(OpenViBE::uint32* states, VisualState ifState, VisualState elseState = NONE);

		protected:
			/**
			 * The stimulator object that generates the stimuli/events given a certain timing
			 */
			CoAdaptP300IStimulator * m_oStimulator;
			
			/**
			 * The tagger to write the stimuli either to OpenViBE's acquisition server or to the parallel port
			 */
			ITagger* m_pTagger;						
			
			/**
			 * OpenViBE's kernel context
			 */
			OpenViBE::Kernel::IKernelContext* m_pKernelContext;
			
			/**
			 * CoAdaptP300PropertyReader that reads the interface-properties file in share/openvibe/applications/CoAdaptP300Stimulator/
			 */
			P300InterfacePropertyReader* m_pInterfacePropReader;
			
			/**
			 * CoAdaptP300PropertyReader that reads one of the keyboard layout files such as 5by10grid-abc-gray.xml in share/openvibe/applications/CoAdaptP300Stimulator/
			 */
			P300ScreenLayoutReader* m_pScreenLayoutReader;
			
			/**
			 * CoAdaptP300PropertyReader that reads the stimulator-properties file in share/openvibe/applications/CoAdaptP300Stimulator/
			 */
			P300StimulatorPropertyReader* m_pStimulatorPropReader;
			
			/**
			 * The main container that will initialize the OpenGL context, the main regions of the P300 keyboard and attach handlers/listeners to them
			 */
			P300MainContainer* m_pMainContainer;
			
			/**
			 * 
			 */
			P300SequenceWriter* m_pSequenceWriter;
			
			/**
			 * 
			 */
			P300SequenceGenerator* m_pSequenceGenerator;

			CoAdaptP300IEvidenceAccumulator* m_oEvidenceAccumulator;

		private:
			/**
			 * A queue with events that should be written by the ITagger
			 */
			std::queue<OpenViBE::uint32> m_qEventQueue;

			std::vector<OpenViBE::uint32>* m_vCurrentFlashGroup;
			
			OpenViBE::boolean m_bChanged;
			OpenViBE::boolean m_bInRest;
			OpenViBE::boolean m_bInFeedback;
			OpenViBE::boolean m_bInTarget;
			OpenViBE::uint32 m_bTargetId;	
			
			OpenViBE::uint32 m_ui32FeedbackCueCounter;
			OpenViBE::uint32 m_ui32FeedbackResultCounter;
			OpenViBE::uint32 m_ui32PreviousFeedbackResultCounter;

			OpenViBE::boolean m_bReplayMode;

			#ifdef OUTPUT_TIMING
            FILE* timingFile;
			FILE* timingFile3;
			#endif
		};
};
#endif//TARGET_HAS_ThirdPartyModulesForCoAdaptStimulator

#endif

