
IF(WIN32)
	FIND_PATH(PATH_TMSi TMSiSDK.dll PATHS ${OV_CUSTOM_DEPENDENCIES_PATH}/sdk-tmsi NO_DEFAULT_PATH)
ENDIF(WIN32)

IF(PATH_TMSi)
	MESSAGE(STATUS "  Found TMSi dll...")

	INSTALL(PROGRAMS "${PATH_TMSi}/TMSiSDK.dll" DESTINATION "bin")
	ADD_DEFINITIONS(-DTARGET_HAS_ThirdPartyTMSi)
ELSE(PATH_TMSi)
	MESSAGE(STATUS "  FAILED to find TMSi device dll (optional)")
ENDIF(PATH_TMSi)
