
IF(WIN32)
	FIND_PATH(PATH_MITSAR MitsarDll.dll PATHS ${OV_CUSTOM_DEPENDENCIES_PATH}/sdk-mitsar NO_DEFAULT_PATH)
ENDIF(WIN32)

IF(PATH_MITSAR)
	MESSAGE(STATUS "  Found Mitsar dll...")

	INSTALL(PROGRAMS "${PATH_MITSAR}/MitsarDll.dll" DESTINATION "bin")
	ADD_DEFINITIONS(-DTARGET_HAS_ThirdPartyMitsar)
ELSE(PATH_MITSAR)
	MESSAGE(STATUS "  FAILED to find Mitsar device dll (optional)")
ENDIF(PATH_MITSAR)
