
IF(WIN32)
	FIND_PATH(PATH_MCS nvxmcs.dll PATHS ${OV_CUSTOM_DEPENDENCIES_PATH}/mcs/lib NO_DEFAULT_PATH)
ENDIF(WIN32)

IF(PATH_MCS)
	MESSAGE(STATUS "  Found MCS device SDK...")
	INCLUDE_DIRECTORIES(${PATH_MCS}/../include/)
	TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${PATH_MCS}/nvxmcs.lib)

	INSTALL(PROGRAMS "${PATH_MCS}/nvxmcs.dll" DESTINATION "bin")
	ADD_DEFINITIONS(-DTARGET_HAS_ThirdPartyMCS)
ELSE(PATH_MCS)
	MESSAGE(STATUS "  FAILED to find MCS device SDK (optional)")
ENDIF(PATH_MCS)
