#!/bin/bash

ov_build_type=Release
if [ "$1" == "--debug" ]; then
	ov_build_type=Debug
	shift
fi
if [ "$1" == "--debug-symbols" ]; then
	ov_build_type=RelWithDebInfo
	shift
fi
if [ "$1" == "--profile" ]; then
	ov_build_type=Profile
	shift
fi

echo ""
echo "_______________________________________________________________________________"
echo ""
		
ov_script_dir="${PWD}"
ov_build_dir="${ov_script_dir}/../local-tmp/linux-${ov_build_type}"
ov_install_dir="${ov_script_dir}/../dist"

mkdir -p "${ov_build_dir}" 2> /dev/null
pushd "${ov_build_dir}" 2> /dev/null

echo ""
echo "Creating makefiles..."
echo ""


if [ ${ov_build_type} == Profile ]; then
	cmake ${ov_script_dir}/.. -DCMAKE_CXX_FLAGS_RELWITHDEBINFO='-O2 -g -DNDEBUG -pg' -DCMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO='-pg' -DCMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO='-pg' -DCMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO='-pg' -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=${ov_install_dir}
else
	cmake ${ov_script_dir}/.. -DCMAKE_BUILD_TYPE=${ov_build_type} -DCMAKE_INSTALL_PREFIX=${ov_install_dir}
fi

 

if [ $? -eq 0 ]; then
	echo CMake has been called successfully !
else
	exit -1
fi;

echo ""
echo "Building ..."
echo ""

NJOBS=`grep processor /proc/cpuinfo | wc -l`
make $1 -j $NJOBS # VERBOSE=1
if [ $? -eq 0 ]; then
	echo Make has been called successfully !
else
	exit -1
fi;

echo ""
echo "Installing files to 'dist' folder, this can take a few seconds - maybe a few minutes..."
echo ""

make install
if [ $? -eq 0 ]; then
	echo Make install has been called successfully !
else
	true # exit -1
fi;

popd 2> /dev/null

echo ""
echo "_______________________________________________________________________________"
echo ""

echo ""
echo "Building process terminated successfully !"
echo ""

echo ""
echo "Install completed !"
echo ""

true
